#
#
#	bo server 1.0
#	other variable define
#
#
BO_NETWORK_LIBS_DIR=$(BO_NETWORK_DIR)/libs
BO_NETWORK_BINS_DIR=$(BO_NETWORK_DIR)/bin
BO_NETWORK_INCLUDE_DIR=$(BO_NETWORK_DIR)/include
BO_NETWORK_SRC_DIR=$(BO_NETWORK_DIR)/src
BO_NETWORK_TEST_DIR=$(BO_NETWORK_DIR)/test

export LD_LIBRARY_PATH=$(BO_NETWORK_DIR)/libs/lib
