#!/bin/bash - 
#===============================================================================
#
#          FILE: mac.sh
# 
#         USAGE: ./mac.sh 
# 
#   DESCRIPTION: 
#           1 用于 Mac 的自启动和自关闭脚本,在 crontab 中定时执行
#           2 定时清除 MAC 上的 Downloads目录,废纸篓
#           3 
# 
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: YOUR NAME (), 
#  ORGANIZATION: 
#       CREATED: 2017/08/25 09:15
#      REVISION:  ---
#===============================================================================

set -o nounset                              # Treat unset variables as an error

APPS=("MySQLWorkbench.app","Google Chrome.app","Evernote.app","WeChat.app",
    "Notion.app", "网易有道词典.app", "Postman.app", "Paste.app", "Typora.app", 
    "Insomnia.app", "Gitter.app", "DingTalk.app", "BestTrace.app")


#---  FUNCTION  ----------------------------------------------------------------
#          NAME:  handle_app
#   DESCRIPTION:  定时启动和关闭所有的应用, 如果已经存在则不操作
#    PARAMETERS:  $1--action
#       RETURNS:  
#-------------------------------------------------------------------------------
handle_app()
{
    OLD_IFS="${IFS}"
    IFS=","
    echo "当前对应用的操作为:" $1
    for app in ${APPS[@]}; do
        if [[ -z "${app}" ]];then
            # echo "Variables ${app} is empty, skip."
            continue
        fi
        if [[ $1 == "start" ]];then
            pids=$(ps -ef|grep ${app}|grep -v grep|awk '{print $2}')
            if [[ ${#pids} -gt 0 ]];then
                echo "App ${app} already opening."
                continue
            fi
            open "/Applications/${app}"
            if [[ $? != 0 ]];then
                echo "Open ${app} failed."
            fi
        elif [[ $1 == "stop" ]];then
            ps -ef|grep ${app}|grep -v grep|awk '{print $2}'|xargs kill -9
            if [[ $? != 0 ]];then
                echo "Kill App ${app} failed."
                continue
            fi
        fi
    done
    IFS=${OLD_IFS}
}


#---  FUNCTION  ----------------------------------------------------------------
#          NAME:  clean
#   DESCRIPTION:  定时清除磁盘指定目录, 指定过期天数的文件,放入 TRASH 中
#           该函数依赖命令trash:https://github.com/morgant/tools-osx
#    PARAMETERS:  
#           $2      指定目录
#           $3      指定过期时间
#       RETURNS:  
#           0/-1
#-------------------------------------------------------------------------------
clean()
{
    if [[ ! -n "$2" || ! -n "$1" ]];then
        echo "Clean函数必须提供两个参数:目录, 时间"
        exit -1
    fi
    
    if [[ $1 =~ "Trash" ]];then
        echo "Go into Trash handle logial!"
        find ${1} -atime +${2}d -maxdepth 1 -print0 | xargs -0 rm -rf
    else
        find ${1} -mtime +${2}d -maxdepth 1 -print0 | xargs -0 /usr/local/bin/trash
    fi
    if [[ $? != 0 ]]; then
        echo "将文件移入 TRASH 失败."
        exit -1
    fi
}


usage()
{
    echo "自动开启以及关闭 APP:"
    echo " start    开启"
    echo " stop     关闭"
}


case "$1" in
    start)
        handle_app  start
        ;;
    stop)
        handle_app  stop
        ;;
    clean)
        clean $2 $3
        ;;
    *)
        usage;;
esac
