#!/usr/local/bin/zsh

# Clear rbenv variables before starting tmux
unset RBENV_VERSION
unset RBENV_DIR

PROJECT=idjango
MAIN_ROOT=~/Public/devproject/unusebamboo
VIM_FILE=manage.py
DRF_ENV='drf'

tmux start-server;

  cd ${MAIN_ROOT}

  # Run pre command.
  

  # Create the session and the first window. 
  # Manually switch to root directory if required to support tmux < 1.9
  TMUX= tmux new-session -d -s ${PROJECT} -n editor
  tmux send-keys -t ${PROJECT}:1 cd\ ${MAIN_ROOT} C-m


  # Create other windows.
  tmux new-window -c ${MAIN_ROOT} -t ${PROJECT}:2 -n server
  tmux new-window -c ${MAIN_ROOT} -t ${PROJECT}:3 -n log


  # Window "editor"
  # 默认打开vim并打开默认文件，这里可以souce vim备份文件
  tmux send-keys -t ${PROJECT}:1.1 workon\ ${DRF_ENV} C-m
  tmux send-keys -t ${PROJECT}:1.1 vim\ ${VIM_FILE} C-m

  # 变动window布局并选择当前active pane
  # tmux select-layout -t ${PROJECT}:1 tiled
  tmux select-layout -t ${PROJECT}:1 main-vertical
  tmux select-pane -t ${PROJECT}:1.1


  # Window server
  tmux send-keys -t ${PROJECT}:2.1 workon\ ${DRF_ENV} C-m
  tmux send-keys -t ${PROJECT}:2.1 python\ manage.py\ runserver\ 0.0.0.0:8080 C-m


  # Window "log"
  # 默认打开队列进程
  tmux send-keys -t ${PROJECT}:3.1 workon\ ${DRF_ENV} C-m

  # 开启日志查看监听
  tmux splitw -c ${MAIN_ROOT} -t ${PROJECT}:3
  tmux select-layout -t ${PROJECT}:3 tiled
  tmux send-keys -t ${PROJECT}:3.2 workon\ ${DRF_ENV} C-m
  # tmux send-keys -t ${PROJECT}:3.2 echo\ "">logs/error.log C-m
  # tmux send-keys -t ${PROJECT}:3.2 tail\ -f\ logs/error.log C-m

  tmux select-layout -t ${PROJECT}:3 main-horizontal
  tmux resize-pane -U 10
  tmux select-pane -t ${PROJECT}:3.1

  # Active windows
  tmux select-window -t 1
  tmux select-pane -t 0

  if [ -z "$TMUX" ]; then
    tmux -u attach-session -t ${PROJECT}
  else
    tmux -u switch-client -t ${PROJECT}
  fi
