#!/usr/local/bin/zsh

# Clear rbenv variables before starting tmux
unset RBENV_VERSION
unset RBENV_DIR

PROJECT=server
PYTHON_ENV=xinshu-service
PRO_NAME=pro
PRO=/home/xinshu/workspace/Xinshu-iLifeDiary-Production/iLifeDiary
BETA_NAME=beta
BETA=/home/xinshu/workspace/Xinshu-iLifeDiary-Beta/iLifeDiary

tmux start-server;

  # 打开pro
  TMUX= tmux new-session -d -s ${PROJECT} -n ${PRO_NAME}
  tmux send-keys -t ${PROJECT}:1 cd C-m
  # 创建主窗口
  tmux send-keys -t ${PROJECT}:1.1 go\ server C-m
  tmux send-keys -t ${PROJECT}:1.1 workon\ ${PYTHON_ENV} C-m
  tmux send-keys -t ${PROJECT}:1.1 cd\ ${PRO} C-m
  tmux select-layout -t ${PROJECT}:1 main-vertical
  tmux select-pane -t ${PROJECT}:1.1
  # # 右上窗口查看book.log
  # tmux send-keys -t ${PROJECT}:1.1 go\ server C-m
  # tmux send-keys -t ${PROJECT}:1.2 workon\ ${PYTHON_ENV} C-m
  # tmux send-keys -t ${PROJECT}:1.2 cd\ ${PRO} C-m
  # tmux send-keys -t ${PROJECT}:1.2 tail -f logs/book.log C-m
  # # 右下窗口准备输入python
  # tmux send-keys -t ${PROJECT}:1.1 go\ server C-m
  # tmux send-keys -t ${PROJECT}:1.3 workon\ ${PYTHON_ENV} C-m
  # tmux send-keys -t ${PROJECT}:1.3 cd\ ${PRO} C-m
  # tmux send-keys -t ${PROJECT}:1.3 python manage.py shell C-m
  # 切换活动窗口
  tmux select-pane -t ${PROJECT}:1.1
  
  
  # # 创建beta
  # tmux new-window -c ${BETA} -t ${PROJECT}:2 -n ${BETA_NAME}
  # 
  # # 创建主窗口
  # tmux send-keys -t ${PROJECT}:2.1 go\ server C-m
  # tmux send-keys -t ${PROJECT}:2.1 cd\ ${BETA} C-m
  # tmux send-keys -t ${PROJECT}:2.1 workon\ ${PYTHON_ENV} C-m
  # tmux select-layout -t ${PROJECT}:2 main-vertical
  # tmux select-pane -t ${PROJECT}:2.1
  # # 右上窗口查看book.log
  # tmux send-keys -t ${PROJECT}:2.2 go\ server C-m
  # tmux send-keys -t ${PROJECT}:2.2 cd\ ${BETA} C-m
  # tmux send-keys -t ${PROJECT}:2.2 workon\ ${PYTHON_ENV} C-m
  # tmux send-keys -t ${PROJECT}:2.2 tail -f logs/book.log C-m
  # # 右下窗口准备输入python
  # tmux send-keys -t ${PROJECT}:2.3 go\ server C-m
  # tmux send-keys -t ${PROJECT}:2.3 cd\ ${BETA} C-m
  # tmux send-keys -t ${PROJECT}:2.3 workon\ ${PYTHON_ENV} C-m
  # tmux send-keys -t ${PROJECT}:2.3 python manage.py shell C-m
  # # 切换活动窗口
  # tmux select-pane -t ${PROJECT}:2.1
  
  tmux select-window -t 1
  tmux select-pane -t 0
  
  if [ -z "$TMUX" ]; then
    tmux -u attach-session -t ${PROJECT}
  else
    tmux -u switch-client -t ${PROJECT}
  fi
