# 1 根据compose配置, 进行镜像的创建, 容器的构建: docker-compose -f web-docker-compose.yml build
# 2 一旦compose发生改动, 可以重新进行构建, 命令同上
# 3 启动服务(自动构建镜像, 创建服务, 启动服务): docker-compose -f web-docker-compose.yml up
version: '3'
services:
    web:
        # 指定镜像名(web:v1)
        image: web:v1
        container_name: web
        # 指定Dockerfile所在文件夹路径, 并自动构建镜像
        build: 
            # Dockerfile所在文件夹的路径
            context: .
            # 指定dockerfile文件名(创建镜像python:3.6-alpine)
            dockerfile: ComposeWebDockerfile
        # 数据卷挂载, 类似命令行-v
        volumes:
            - ~/Documents/docker/:/docker/
        # 暴露端口信息, Host:Container格式, 其中Host表示宿主端口
        ports:
            - "8002:8002"
        # 容器依赖问题
        depends_on:
            - redis

    # 指定镜像名(redis:alpine), 作为web:v1的依赖
    redis:
        image: "redis:alpine"
        container_name: redis
