log: # 日志配置
  # 日志路径
  dir: "./log"

redis:  # redis配置
    addr: 127.0.0.1:6379
    password: ""
    # 连接池大小
    poolSize: 10
    # 连接超时时间
    dialTimeout: 100ms
    # 读超时时间
    readTimeout: 500ms
    # 写超时时间
    writeTimeout: 300ms
  
mysql:
  # GRANT ALL PRIVILEGES ON bamboodba.* TO 'bamboo'@'%' WITH GRANT OPTION;
  bambooweb:
    database: bamboodba
    addr: 127.0.0.1:3306
    user: bamboo
    password: bamboodba
    connTimeout: 300ms
    readTimeOut: 500ms
    writeTimeOut: 500ms
    MaxIdleConns: 10
    MaxOpenConns: 10
    ConnMaxLifeTime: 3m

  bamboowebtest:
    database: bamboodbatest
    addr: 127.0.0.1:3306
    user: bambootest
    password: bamboodbatest
    connTimeout: 300ms
    readTimeOut: 500ms
    writeTimeOut: 500ms
    MaxIdleConns: 10
    MaxOpenConns: 10
    ConnMaxLifeTime: 3m